start:
    path: /
    defaults: { _controller: AppBundle:Jednostka:index}

app_jednostka:
    resource: '@AppBundle/Resources/config/routing/jednostka.php'
    prefix: /jednostka


app_grupa:
    resource: '@AppBundle/Resources/config/routing/grupa.php'
    prefix: /grupa

app_material:
    resource: '@AppBundle/Resources/config/routing/material.php'
    prefix: /material
