jednostka_index:
  path:   /
  defaults: { _controller:AppBundle:Jednostka:Index }

jednostka_show:
  path:     /{id}/show
  defaults: { _controller:AppBundle:Jednostka:Show }

jednostka_edit:
  path:     /{id}/edit
  defaults: { _controller:AppBundle:Jednostka:Edit }

jednostka_new:
  path:     /new
  defaults: { _controller:AppBundle:Jednostka:New }

jednostka_delete:
  path:     /{id}/delete
  defaults: { _controller:AppBundle:Jednostka:Delete }
  methods:  [DELETE]
